---
title: "README"
author: "Niamh Phillips"
date: "05/06/2020"
output: html_document
---
This purpose of this project is to demonstrate my ability to retrieve and clean a data set so it can be used for later use. 

A link to the data used in the project:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

 1) run_analysis.R file containing the data retrieving and cleaning along with the 5 tasks required
 
- Merges the training and the test sets to create one data set.
- Extracts only the measurements on the mean and standard deviation for each measurement.
- Uses descriptive activity names to name the activities in the data set
- Appropriately labels the data set with descriptive variable names.
- From the data set in step 4, creates a second, independent tidy data set with the average of   each variable for each activity and each subject.
 
 2) coodebook_gettingCleaningData.rmd indicates all the variables and summaries calculated, along with units, and any other relevant information.
 



